/** Isolated pre-Host enterprise login window with a strict action/result channel. */

import { BrowserWindow } from 'electron'
import { fileURLToPath } from 'node:url'
import {
  auxiliaryWindowChromeOptions,
  auxiliaryWindowHasCustomFrame,
} from './auxiliary-window-options.ts'
import { revealApplication } from './electron-reveal.ts'
import type { DesktopLocale } from './runtime.ts'
import { enterpriseLoginCopy, type EnterpriseLoginView } from './enterprise-login-copy.ts'

const LOGIN_DOCUMENT = fileURLToPath(new URL('./native-ui/enterprise-login.html', import.meta.url))
const MAX_ACTION_BYTES = 1024
const ACTION_NAMES = Object.freeze(['open-browser', 'copy-link', 'retry', 'back'] as const)
export type EnterpriseLoginWindowAction = (typeof ACTION_NAMES)[number]
const TERMINAL_ACTIONS = Object.freeze(['continue'] as const)

/** Window input rendered into the document; the state never carries secrets. */
export interface DesktopEnterpriseLoginWindowInput {
  readonly view: EnterpriseLoginView
  /** Read-only organization gateway origin shown for phishing-resistance (R15). */
  readonly serverOrigin: string
  readonly username?: string
  readonly timeoutMinutes: number
  readonly errorMessage?: string
  /** Non-fatal notice shown above the view content (e.g. refresh-failure re-login). */
  readonly notice?: 'session-expired'
}

export interface DesktopEnterpriseLoginWindowOptions {
  readonly locale: DesktopLocale
  readonly platform: NodeJS.Platform
  readonly input: DesktopEnterpriseLoginWindowInput
  /** Non-terminal renderer actions forwarded to the owning gate. */
  readonly onAction: (action: EnterpriseLoginWindowAction) => void
}

/** Outcome that ends the one-shot login window. */
export type DesktopEnterpriseLoginResult =
  | { readonly action: 'continue' }
  | { readonly action: 'quit' }

function exactAction(value: string): EnterpriseLoginWindowAction | undefined {
  return (ACTION_NAMES as readonly string[]).includes(value)
    ? value as EnterpriseLoginWindowAction
    : undefined
}

/** Parse only a bounded action generated by the local login document. */
export function parseDesktopEnterpriseLoginAction(
  href: string,
): EnterpriseLoginWindowAction | 'continue' | undefined {
  if (new TextEncoder().encode(href).byteLength > MAX_ACTION_BYTES) return undefined
  // The renderer assigns `dsh-enterprise-login:<action>`; browsers canonicalize
  // custom schemes into either the opaque-path or the authority form, so both
  // spellings are accepted and anything else (query, hash, extra segments) is
  // rejected instead of guessed.
  const match = /^dsh-enterprise-login:(?:\/\/)?([A-Za-z0-9-]+)\/?$/u.exec(href)
  if (match === null) return undefined
  const name = match[1] ?? ''
  if ((TERMINAL_ACTIONS as readonly string[]).includes(name)) return 'continue'
  return exactAction(name)
}

/** One-shot native login window; main drives views by reloading the document. */
export class DesktopEnterpriseLoginWindow {
  private started = false
  private window: BrowserWindow | undefined
  private currentInput: DesktopEnterpriseLoginWindowInput

  constructor(private readonly options: DesktopEnterpriseLoginWindowOptions) {
    this.currentInput = options.input
  }

  /** Bring the running login window forward for activation and second-instance events. */
  show(): void {
    const window = this.window
    if (window === undefined || window.isDestroyed()) return
    revealApplication(window, this.options.platform)
  }

  get isRunning(): boolean {
    return this.window !== undefined
  }

  /** Push a new view into the window (or no-op when it is already closed). */
  showView(input: DesktopEnterpriseLoginWindowInput): void {
    this.currentInput = input
    const window = this.window
    if (window === undefined || window.isDestroyed()) return
    void window.loadFile(LOGIN_DOCUMENT, { query: this.documentQuery(input) }).catch(() => undefined)
  }

  private documentQuery(input: DesktopEnterpriseLoginWindowInput): Record<string, string> {
    const state = Buffer.from(JSON.stringify(input), 'utf8').toString('base64url')
    return {
      locale: this.options.locale,
      platform: this.options.platform,
      frame: String(auxiliaryWindowHasCustomFrame(this.options.platform)),
      state,
    }
  }

  async run(): Promise<DesktopEnterpriseLoginResult> {
    if (this.started) throw new Error('dsh-plugin-desktop: enterprise login window can only run once')
    this.started = true
    const copy = enterpriseLoginCopy(this.options.locale)
    const window = new BrowserWindow({
      title: copy.title,
      ...auxiliaryWindowChromeOptions(this.options.platform),
      width: 480,
      height: 560,
      useContentSize: true,
      minWidth: 420,
      minHeight: 460,
      resizable: true,
      maximizable: false,
      fullscreenable: false,
      show: this.options.platform === 'win32',
      autoHideMenuBar: true,
      backgroundColor: '#202124',
      webPreferences: {
        contextIsolation: true,
        nodeIntegration: false,
        nodeIntegrationInSubFrames: false,
        sandbox: true,
        webSecurity: true,
        webviewTag: false,
        spellcheck: false,
        partition: 'dsh-enterprise-login',
      },
    })
    this.window = window
    window.accessibleTitle = copy.title
    window.removeMenu()
    window.webContents.setWindowOpenHandler(() => ({ action: 'deny' }))
    window.webContents.on('will-attach-webview', event => { event.preventDefault() })

    return await new Promise<DesktopEnterpriseLoginResult>((resolve, reject) => {
      let settled = false
      const finish = (result: DesktopEnterpriseLoginResult): void => {
        if (settled) return
        settled = true
        if (this.window === window) this.window = undefined
        if (!window.isDestroyed()) window.destroy()
        resolve(result)
      }
      const navigate = (event: Electron.Event, href: string): void => {
        event.preventDefault()
        const action = parseDesktopEnterpriseLoginAction(href)
        if (action === undefined) return
        if (action === 'continue') {
          finish(Object.freeze({ action: 'continue' }))
          return
        }
        this.options.onAction(action)
      }
      window.webContents.on('will-navigate', navigate)
      window.webContents.on('will-redirect', navigate)
      window.once('ready-to-show', () => {
        if (!settled && this.window === window && !window.isDestroyed()) {
          revealApplication(window, this.options.platform)
        }
      })
      window.on('closed', () => {
        if (this.window === window) this.window = undefined
        finish(Object.freeze({ action: 'quit' }))
      })
      void window.loadFile(LOGIN_DOCUMENT, { query: this.documentQuery(this.currentInput) }).catch((cause: unknown) => {
        if (settled) return
        settled = true
        if (this.window === window) this.window = undefined
        if (!window.isDestroyed()) window.destroy()
        reject(cause)
      })
    })
  }
}
