/** Machine-level Cordis patch that locks the enterprise model route (brief 13.3). */

import { mkdir, readFile } from 'node:fs/promises'
import { join } from 'node:path'
import { writeFileAtomic } from '@deepseek-ai/dsh-atomic-write'

const BIN_NAME = 'dsh-plugin-desktop'
/** Marker identifying the generated document so admin-authored files stay untouched. */
export const ENTERPRISE_MACHINE_PATCH_MARKER = 'Generated by DSH Desktop enterprise enrollment'
export const ENTERPRISE_LLM_ROUTE = 'dsh-enterprise'
export const ENTERPRISE_LLM_API_KEY_ENV = 'DSH_LLM_TOKEN'
/** Server-side llm-egress prefix; the gateway serves the OpenAI surface beneath it. */
export const ENTERPRISE_LLM_EGRESS_PATH = '/internal/llm'
const PATCH_FILENAME = 'cordis.patch.yml'

/** Default model catalog; DeepSeek-first per the platform design, adjust per deployment. */
const DEFAULT_MODELS = [
  { id: 'deepseek-chat', name: 'DeepSeek Chat' },
  { id: 'deepseek-reasoner', name: 'DeepSeek Reasoner' },
] as const

/**
 * Render the machine patch document. The route merges into the base bundle's
 * dormant `llm-pi-ai` entry (routes are a per-provider dict), pinning the
 * endpoint to the organization gateway's llm-egress and the credential to the
 * `DSH_LLM_TOKEN` environment name that the enterprise runtime injects.
 */
export function renderEnterpriseMachinePatch(options: {
  readonly gatewayUrl: string
  readonly models?: readonly { readonly id: string, readonly name: string }[]
}): string {
  const baseURL = `${options.gatewayUrl.replace(/\/+$/u, '')}${ENTERPRISE_LLM_EGRESS_PATH}`
  const models = options.models ?? DEFAULT_MODELS
  const modelLines = models.map(model => `          - id: ${JSON.stringify(model.id)}\n            name: ${JSON.stringify(model.name)}`).join('\n')
  return `# ${ENTERPRISE_MACHINE_PATCH_MARKER}.
# It locks one model route to the organization gateway so Desktop model
# traffic leaves only through the gateway's llm-egress. Adjust the model list
# if your deployment's allowlist differs. Remove this file to unenroll.
- id: llm-pi-ai
  config:
    providers:
      ${ENTERPRISE_LLM_ROUTE}:
        displayName: DSH Enterprise Gateway
        apiKeyEnv: ${ENTERPRISE_LLM_API_KEY_ENV}
        api: openai-completions
        baseURL: ${JSON.stringify(baseURL)}
        models:
${modelLines}
`
}

export type EnterpriseMachinePatchOutcome =
  | { readonly status: 'written' }
  | { readonly status: 'updated' }
  | { readonly status: 'unchanged' }
  | { readonly status: 'admin-file-kept' }

/**
 * Idempotently install the machine patch below the DSH home directory. An
 * existing generated document is kept in sync with the preset; any other
 * existing document is admin-owned and is left untouched.
 */
export async function writeEnterpriseMachinePatch(
  homeDir: string,
  document: string,
): Promise<EnterpriseMachinePatchOutcome> {
  const path = join(homeDir, PATCH_FILENAME)
  let existing: string | undefined
  try {
    existing = await readFile(path, 'utf8')
  } catch (cause) {
    if ((cause as NodeJS.ErrnoException).code !== 'ENOENT') {
      throw new Error(`${BIN_NAME}: machine patch file could not be inspected: ${String(cause)}`)
    }
  }
  if (existing !== undefined && !existing.includes(ENTERPRISE_MACHINE_PATCH_MARKER)) {
    return Object.freeze({ status: 'admin-file-kept' })
  }
  if (existing === document) return Object.freeze({ status: 'unchanged' })
  await mkdir(homeDir, { recursive: true })
  await writeFileAtomic(path, document, { mode: 0o644, dirMode: 0o755 })
  return Object.freeze({ status: existing === undefined ? 'written' : 'updated' })
}
